import QtQuick 1.1
// Generated by meego/tests/make-stubs.sh from the real component;
// only the API surface, so that the checker sees what the device has.
Item {
    property bool checkable
    property bool checked
    property variant font
    property url iconSource
    property variant platformMouseAnchors
    property variant platformStyle
    property variant pressed
    property variant style
    property variant text
    signal clicked()
}
